In [1]:
print("heyaaaa")


heyaaaa


In [2]:
import numpy as np
import pandas as pd  

In [3]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [4]:
diabetes_dataset= pd.read_csv("../datasets/diabetes.csv")

In [5]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
diabetes_dataset.shape

(768, 9)

In [8]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [10]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [6]:
x= diabetes_dataset.drop(columns=['Outcome'],axis=1)
y= diabetes_dataset['Outcome']

In [12]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [13]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [7]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_final, Y_final = smote.fit_resample(x, y)
print(Y_final.value_counts())

Outcome
1    500
0    500
Name: count, dtype: int64


In [8]:
X_train, X_test, Y_train, Y_test=train_test_split(X_final, Y_final,test_size=0.2,random_state=42)

In [16]:
X_train.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin        BMI  \
29             5      117             92              0        0  34.100000   
535            4      132              0              0        0  32.900000   
695            7      142             90             24      480  30.400000   
557            8      110             76              0        0  27.800000   
836            0      121             66             30      165  34.451261   

     DiabetesPedigreeFunction  Age  
29                    0.33700   38  
535                   0.30200   23  
695                   0.12800   43  
557                   0.23700   58  
836                   0.22016   32

In [17]:
X_train.shape


(800, 8)

In [19]:

Y_train.head()


29     0
535    1
695    1
557    0
836    1
Name: Outcome, dtype: int64

In [20]:

Y_train.shape

(800,)

In [21]:

Y_test.shape

(200,)

In [22]:

Y_test.head()


521    0
737    0
740    1
660    0
411    0
Name: Outcome, dtype: int64

In [9]:
model = svm.SVC(kernel='linear')

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
model.fit(X_train_scaled,Y_train)

SVC(kernel='linear')

In [12]:
y_pred = model.predict(X_test_scaled)
x_pred = model.predict(X_train_scaled)

In [13]:
print(accuracy_score(Y_test,y_pred))

0.7


In [14]:
print(accuracy_score(Y_train,x_pred))

0.74375


In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))
print("Classification Report:\n", classification_report(Y_test, y_pred))

Confusion Matrix:
 [[71 28]
 [32 69]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.72      0.70        99
           1       0.71      0.68      0.70       101

    accuracy                           0.70       200
   macro avg       0.70      0.70      0.70       200
weighted avg       0.70      0.70      0.70       200



In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train_scaled, Y_train)

RandomForestClassifier()

In [17]:
y_pred = model.predict(X_test_scaled)
x_pred = model.predict(X_train_scaled)

In [18]:
print(accuracy_score(Y_test,y_pred))

0.805


In [19]:
print(accuracy_score(Y_train,x_pred))

1.0


In [20]:
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[74 25]
 [14 87]]


In [ ]:
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", cm)

In [21]:
cr = classification_report(Y_test, y_pred)
print("Classification Report:\n", cr)

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.75      0.79        99
           1       0.78      0.86      0.82       101

    accuracy                           0.81       200
   macro avg       0.81      0.80      0.80       200
weighted avg       0.81      0.81      0.80       200



In [22]:
pip install pickle

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pickle


In [24]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42
)
model.fit(X_train_scaled, Y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, random_state=42)

In [25]:
y_pred = model.predict(X_test_scaled)
x_pred = model.predict(X_train_scaled)

In [26]:
print(accuracy_score(Y_test,y_pred))

0.78


In [27]:
print(accuracy_score(Y_test,y_pred))

0.78


In [28]:
cm = confusion_matrix(Y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[72 27]
 [17 84]]


In [30]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['log2', 'sqrt']
}

rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(estimator=rf, param_grid=param_grid,
                           cv=5, n_jobs=-1, scoring='accuracy')
grid_search.fit(X_train_scaled, Y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

Best Parameters: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}
Best Accuracy: 0.82125


In [38]:
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=2,
    max_features='sqrt',
    random_state=42
)
model.fit(X_train_scaled, Y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, random_state=42)

In [39]:
y_pred = model.predict(X_test_scaled)
x_pred = model.predict(X_train_scaled)
print(accuracy_score(Y_test,y_pred))

0.77


In [40]:
print(accuracy_score(Y_train,x_pred))

0.97625


In [41]:
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(Y_test, y_pred))

Accuracy: 0.77


In [43]:
y_train_pred = best_model.predict(X_train_scaled)

# Calculate training accuracy
train_accuracy = accuracy_score(Y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.97625


In [44]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(X_train_scaled, Y_train)

# Step 3: Predict
y_train_pred = log_model.predict(X_train_scaled)
y_test_pred = log_model.predict(X_test_scaled)

# Step 4: Evaluate
print("Training Accuracy:", accuracy_score(Y_train, y_train_pred))
print("Testing Accuracy:", accuracy_score(Y_test, y_test_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_test_pred))

print("\nClassification Report:")
print(classification_report(Y_test, y_test_pred))

Training Accuracy: 0.75
Testing Accuracy: 0.705

Confusion Matrix:
[[71 28]
 [31 70]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.72      0.71        99
           1       0.71      0.69      0.70       101

    accuracy                           0.70       200
   macro avg       0.71      0.71      0.70       200
weighted avg       0.71      0.70      0.70       200



In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Define model
logreg = LogisticRegression(max_iter=1000)

# Define parameters grid to search
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],   # Regularization strength
    'penalty': ['l1', 'l2'],                # L1 = Lasso, L2 = Ridge regularization
    'solver': ['liblinear']                  # Solver that supports l1 penalty
}

# Setup GridSearchCV
grid_search = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit GridSearch to your training data
grid_search.fit(X_train_scaled, Y_train)

# Best params and best score
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

# Predict on test using the best estimator
best_logreg = grid_search.best_estimator_
y_pred_test = best_logreg.predict(X_test_scaled)
y_pred_train = best_logreg.predict(X_train_scaled)

# Evaluate performance

print("Test Accuracy:", accuracy_score(Y_test, y_pred_test))
print("Train Accuracy:", accuracy_score(Y_train, y_pred_train))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_test))
print("Classification Report:\n", classification_report(Y_test, y_pred_test))

Best Parameters: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
Best Accuracy: 0.7362500000000001
Test Accuracy: 0.705
Train Accuracy: 0.73875
Confusion Matrix:
 [[71 28]
 [31 70]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.72      0.71        99
           1       0.71      0.69      0.70       101

    accuracy                           0.70       200
   macro avg       0.71      0.71      0.70       200
weighted avg       0.71      0.70      0.70       200



In [50]:

param_grid = {
    'C': [0.1, 1, 10],
    'gamma': [0.01, 0.1, 1],
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid']
}
grid = GridSearchCV(svm.SVC(), param_grid, refit=True, verbose=2, cv=5)
grid.fit(X_train_scaled, Y_train)

print("Best Parameters:", grid.best_params_)
print("Best Cross-Validated Accuracy:", grid.best_score_)





Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ...................C=0.1, gamma=0.01, kernel=linear; total time=   0.0s
[CV] END ...................C=0.1, gamma=0.01, kernel=linear; total time=   0.0s
[CV] END ...................C=0.1, gamma=0.01, kernel=linear; total time=   0.0s
[CV] END ...................C=0.1, gamma=0.01, kernel=linear; total time=   0.0s
[CV] END ...................C=0.1, gamma=0.01, kernel=linear; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.01, kernel=poly; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.01

In [56]:
best_model = grid.best_estimator_
y_pred_test = best_model.predict(X_test_scaled)
y_pred_train = best_model.predict(X_train_scaled)
print("Test Accuracy:", accuracy_score(Y_test, y_pred_test))
print("Train Accuracy:", accuracy_score(Y_train,y_pred_train ))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_test))
print("Classification Report:\n", classification_report(Y_test, y_pred_test))

Test Accuracy: 0.73
Train Accuracy: 0.89125
Confusion Matrix:
 [[67 32]
 [22 79]]
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.68      0.71        99
           1       0.71      0.78      0.75       101

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.73      0.73      0.73       200



In [54]:
print(grid.best_params_) 

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}


In [57]:
import pickle
pickle.dump(scaler, open('diabetes_scaler.sav', 'wb'))
pickle.dump(best_model, open('diabetes_model.sav', 'wb'))

In [58]:
scaler = pickle.load(open('diabetes_scaler.sav', 'rb'))
model = pickle.load(open('diabetes_model.sav', 'rb'))

In [60]:
new_input = [5,166,72,19,175,25.8,0.587,51]

# Convert to numpy array and reshape (1 sample, 8 features)
new_input_np = np.array(new_input).reshape(1, -1)

# Scale the input using the loaded scaler
new_input_scaled = scaler.transform(new_input_np)

# Predict using the loaded model
prediction = model.predict(new_input_scaled)

# Print prediction result
if prediction[0] == 1:
    print("The model predicts: Diabetes Positive")
else:
    print("The model predicts: Diabetes Negative")

The model predicts: Diabetes Positive


C:\Users\nachhattarsingh\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
